### ISSUE TITLE
Avoid using port 80

### ISSUE THREAD

**Issue by ahmednosman** [GeoNode/geonode-win-installer#2]
in most windows server machines this port will be already taken by IIS
In case of usage of online hosting this port always default to IIS
Best option is to test for port availability and assign consecutive ports and avoiding most common used ports, example
geoserver 8082
geonode   8083
postgis      8084 (also avoid default here, might have opengeosuite or similar already installed)

**Comment by afabiani** [comment]
That should be fixed with the latest commits.
